// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agglayer/interop/types/v1/bridge_exit.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of the leaf.
type LeafType int32

const (
	// Unspecified leaf type.
	LeafType_LEAF_TYPE_UNSPECIFIED LeafType = 0
	// Transfer leaf type.
	LeafType_LEAF_TYPE_TRANSFER LeafType = 1
	// Message leaf type.
	LeafType_LEAF_TYPE_MESSAGE LeafType = 2
)

// Enum value maps for LeafType.
var (
	LeafType_name = map[int32]string{
		0: "LEAF_TYPE_UNSPECIFIED",
		1: "LEAF_TYPE_TRANSFER",
		2: "LEAF_TYPE_MESSAGE",
	}
	LeafType_value = map[string]int32{
		"LEAF_TYPE_UNSPECIFIED": 0,
		"LEAF_TYPE_TRANSFER":    1,
		"LEAF_TYPE_MESSAGE":     2,
	}
)

func (x LeafType) Enum() *LeafType {
	p := new(LeafType)
	*p = x
	return p
}

func (x LeafType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeafType) Descriptor() protoreflect.EnumDescriptor {
	return file_agglayer_interop_types_v1_bridge_exit_proto_enumTypes[0].Descriptor()
}

func (LeafType) Type() protoreflect.EnumType {
	return &file_agglayer_interop_types_v1_bridge_exit_proto_enumTypes[0]
}

func (x LeafType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeafType.Descriptor instead.
func (LeafType) EnumDescriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_bridge_exit_proto_rawDescGZIP(), []int{0}
}

// Represents a token bridge exit from the network.
type BridgeExit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the leaf.
	LeafType LeafType `protobuf:"varint,1,opt,name=leaf_type,json=leafType,proto3,enum=agglayer.interop.types.v1.LeafType" json:"leaf_type,omitempty"`
	// Unique ID for the token being transferred.
	TokenInfo *TokenInfo `protobuf:"bytes,2,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	// Network which the token is transferred to
	DestNetwork uint32 `protobuf:"varint,3,opt,name=dest_network,json=destNetwork,proto3" json:"dest_network,omitempty"`
	// Address which will own the received token
	DestAddress *FixedBytes20 `protobuf:"bytes,4,opt,name=dest_address,json=destAddress,proto3" json:"dest_address,omitempty"`
	// Token amount sent, stored big-endian
	Amount *FixedBytes32 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// Metadata for the bridge exit
	Metadata      *FixedBytes32 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeExit) Reset() {
	*x = BridgeExit{}
	mi := &file_agglayer_interop_types_v1_bridge_exit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeExit) ProtoMessage() {}

func (x *BridgeExit) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_bridge_exit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeExit.ProtoReflect.Descriptor instead.
func (*BridgeExit) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_bridge_exit_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeExit) GetLeafType() LeafType {
	if x != nil {
		return x.LeafType
	}
	return LeafType_LEAF_TYPE_UNSPECIFIED
}

func (x *BridgeExit) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *BridgeExit) GetDestNetwork() uint32 {
	if x != nil {
		return x.DestNetwork
	}
	return 0
}

func (x *BridgeExit) GetDestAddress() *FixedBytes20 {
	if x != nil {
		return x.DestAddress
	}
	return nil
}

func (x *BridgeExit) GetAmount() *FixedBytes32 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BridgeExit) GetMetadata() *FixedBytes32 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Encapsulates the information to uniquely identify a token on the origin
// network.
type TokenInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network which the token originates from
	OriginNetwork uint32 `protobuf:"varint,1,opt,name=origin_network,json=originNetwork,proto3" json:"origin_network,omitempty"`
	// The address of the token on the origin network
	OriginTokenAddress *FixedBytes20 `protobuf:"bytes,2,opt,name=origin_token_address,json=originTokenAddress,proto3" json:"origin_token_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_agglayer_interop_types_v1_bridge_exit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_bridge_exit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_bridge_exit_proto_rawDescGZIP(), []int{1}
}

func (x *TokenInfo) GetOriginNetwork() uint32 {
	if x != nil {
		return x.OriginNetwork
	}
	return 0
}

func (x *TokenInfo) GetOriginTokenAddress() *FixedBytes20 {
	if x != nil {
		return x.OriginTokenAddress
	}
	return nil
}

var File_agglayer_interop_types_v1_bridge_exit_proto protoreflect.FileDescriptor

const file_agglayer_interop_types_v1_bridge_exit_proto_rawDesc = "" +
	"\n" +
	"+agglayer/interop/types/v1/bridge_exit.proto\x12\x19agglayer.interop.types.v1\x1a%agglayer/interop/types/v1/bytes.proto\"\x88\x03\n" +
	"\n" +
	"BridgeExit\x12@\n" +
	"\tleaf_type\x18\x01 \x01(\x0e2#.agglayer.interop.types.v1.LeafTypeR\bleafType\x12C\n" +
	"\n" +
	"token_info\x18\x02 \x01(\v2$.agglayer.interop.types.v1.TokenInfoR\ttokenInfo\x12!\n" +
	"\fdest_network\x18\x03 \x01(\rR\vdestNetwork\x12J\n" +
	"\fdest_address\x18\x04 \x01(\v2'.agglayer.interop.types.v1.FixedBytes20R\vdestAddress\x12?\n" +
	"\x06amount\x18\x05 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\x06amount\x12C\n" +
	"\bmetadata\x18\x06 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\bmetadata\"\x8d\x01\n" +
	"\tTokenInfo\x12%\n" +
	"\x0eorigin_network\x18\x01 \x01(\rR\roriginNetwork\x12Y\n" +
	"\x14origin_token_address\x18\x02 \x01(\v2'.agglayer.interop.types.v1.FixedBytes20R\x12originTokenAddress*T\n" +
	"\bLeafType\x12\x19\n" +
	"\x15LEAF_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LEAF_TYPE_TRANSFER\x10\x01\x12\x15\n" +
	"\x11LEAF_TYPE_MESSAGE\x10\x02b\x06proto3"

var (
	file_agglayer_interop_types_v1_bridge_exit_proto_rawDescOnce sync.Once
	file_agglayer_interop_types_v1_bridge_exit_proto_rawDescData []byte
)

func file_agglayer_interop_types_v1_bridge_exit_proto_rawDescGZIP() []byte {
	file_agglayer_interop_types_v1_bridge_exit_proto_rawDescOnce.Do(func() {
		file_agglayer_interop_types_v1_bridge_exit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_bridge_exit_proto_rawDesc), len(file_agglayer_interop_types_v1_bridge_exit_proto_rawDesc)))
	})
	return file_agglayer_interop_types_v1_bridge_exit_proto_rawDescData
}

var file_agglayer_interop_types_v1_bridge_exit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agglayer_interop_types_v1_bridge_exit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agglayer_interop_types_v1_bridge_exit_proto_goTypes = []any{
	(LeafType)(0),        // 0: agglayer.interop.types.v1.LeafType
	(*BridgeExit)(nil),   // 1: agglayer.interop.types.v1.BridgeExit
	(*TokenInfo)(nil),    // 2: agglayer.interop.types.v1.TokenInfo
	(*FixedBytes20)(nil), // 3: agglayer.interop.types.v1.FixedBytes20
	(*FixedBytes32)(nil), // 4: agglayer.interop.types.v1.FixedBytes32
}
var file_agglayer_interop_types_v1_bridge_exit_proto_depIdxs = []int32{
	0, // 0: agglayer.interop.types.v1.BridgeExit.leaf_type:type_name -> agglayer.interop.types.v1.LeafType
	2, // 1: agglayer.interop.types.v1.BridgeExit.token_info:type_name -> agglayer.interop.types.v1.TokenInfo
	3, // 2: agglayer.interop.types.v1.BridgeExit.dest_address:type_name -> agglayer.interop.types.v1.FixedBytes20
	4, // 3: agglayer.interop.types.v1.BridgeExit.amount:type_name -> agglayer.interop.types.v1.FixedBytes32
	4, // 4: agglayer.interop.types.v1.BridgeExit.metadata:type_name -> agglayer.interop.types.v1.FixedBytes32
	3, // 5: agglayer.interop.types.v1.TokenInfo.origin_token_address:type_name -> agglayer.interop.types.v1.FixedBytes20
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_agglayer_interop_types_v1_bridge_exit_proto_init() }
func file_agglayer_interop_types_v1_bridge_exit_proto_init() {
	if File_agglayer_interop_types_v1_bridge_exit_proto != nil {
		return
	}
	file_agglayer_interop_types_v1_bytes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_bridge_exit_proto_rawDesc), len(file_agglayer_interop_types_v1_bridge_exit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agglayer_interop_types_v1_bridge_exit_proto_goTypes,
		DependencyIndexes: file_agglayer_interop_types_v1_bridge_exit_proto_depIdxs,
		EnumInfos:         file_agglayer_interop_types_v1_bridge_exit_proto_enumTypes,
		MessageInfos:      file_agglayer_interop_types_v1_bridge_exit_proto_msgTypes,
	}.Build()
	File_agglayer_interop_types_v1_bridge_exit_proto = out.File
	file_agglayer_interop_types_v1_bridge_exit_proto_goTypes = nil
	file_agglayer_interop_types_v1_bridge_exit_proto_depIdxs = nil
}
