// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agglayer/interop/types/v1/bytes.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FixedBytes65 type.
type FixedBytes65 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes representation of the bytearray.
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedBytes65) Reset() {
	*x = FixedBytes65{}
	mi := &file_agglayer_interop_types_v1_bytes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedBytes65) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedBytes65) ProtoMessage() {}

func (x *FixedBytes65) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_bytes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedBytes65.ProtoReflect.Descriptor instead.
func (*FixedBytes65) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_bytes_proto_rawDescGZIP(), []int{0}
}

func (x *FixedBytes65) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// FixedBytes32 type.
type FixedBytes32 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes representation of the bytearray.
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedBytes32) Reset() {
	*x = FixedBytes32{}
	mi := &file_agglayer_interop_types_v1_bytes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedBytes32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedBytes32) ProtoMessage() {}

func (x *FixedBytes32) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_bytes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedBytes32.ProtoReflect.Descriptor instead.
func (*FixedBytes32) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_bytes_proto_rawDescGZIP(), []int{1}
}

func (x *FixedBytes32) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// FixedBytes20 type.
type FixedBytes20 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes representation of the bytearray.
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedBytes20) Reset() {
	*x = FixedBytes20{}
	mi := &file_agglayer_interop_types_v1_bytes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedBytes20) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedBytes20) ProtoMessage() {}

func (x *FixedBytes20) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_bytes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedBytes20.ProtoReflect.Descriptor instead.
func (*FixedBytes20) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_bytes_proto_rawDescGZIP(), []int{2}
}

func (x *FixedBytes20) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_agglayer_interop_types_v1_bytes_proto protoreflect.FileDescriptor

const file_agglayer_interop_types_v1_bytes_proto_rawDesc = "" +
	"\n" +
	"%agglayer/interop/types/v1/bytes.proto\x12\x19agglayer.interop.types.v1\"$\n" +
	"\fFixedBytes65\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"$\n" +
	"\fFixedBytes32\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"$\n" +
	"\fFixedBytes20\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05valueb\x06proto3"

var (
	file_agglayer_interop_types_v1_bytes_proto_rawDescOnce sync.Once
	file_agglayer_interop_types_v1_bytes_proto_rawDescData []byte
)

func file_agglayer_interop_types_v1_bytes_proto_rawDescGZIP() []byte {
	file_agglayer_interop_types_v1_bytes_proto_rawDescOnce.Do(func() {
		file_agglayer_interop_types_v1_bytes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_bytes_proto_rawDesc), len(file_agglayer_interop_types_v1_bytes_proto_rawDesc)))
	})
	return file_agglayer_interop_types_v1_bytes_proto_rawDescData
}

var file_agglayer_interop_types_v1_bytes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agglayer_interop_types_v1_bytes_proto_goTypes = []any{
	(*FixedBytes65)(nil), // 0: agglayer.interop.types.v1.FixedBytes65
	(*FixedBytes32)(nil), // 1: agglayer.interop.types.v1.FixedBytes32
	(*FixedBytes20)(nil), // 2: agglayer.interop.types.v1.FixedBytes20
}
var file_agglayer_interop_types_v1_bytes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agglayer_interop_types_v1_bytes_proto_init() }
func file_agglayer_interop_types_v1_bytes_proto_init() {
	if File_agglayer_interop_types_v1_bytes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_bytes_proto_rawDesc), len(file_agglayer_interop_types_v1_bytes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agglayer_interop_types_v1_bytes_proto_goTypes,
		DependencyIndexes: file_agglayer_interop_types_v1_bytes_proto_depIdxs,
		MessageInfos:      file_agglayer_interop_types_v1_bytes_proto_msgTypes,
	}.Build()
	File_agglayer_interop_types_v1_bytes_proto = out.File
	file_agglayer_interop_types_v1_bytes_proto_goTypes = nil
	file_agglayer_interop_types_v1_bytes_proto_depIdxs = nil
}
