// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agglayer/interop/types/v1/claim.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a claim from the mainnet.
type ClaimFromMainnet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Proof from bridge exit leaf to MER
	ProofLeafMer *MerkleProof `protobuf:"bytes,1,opt,name=proof_leaf_mer,json=proofLeafMer,proto3" json:"proof_leaf_mer,omitempty"`
	// Proof from GER to L1Root
	ProofGerL1Root *MerkleProof `protobuf:"bytes,2,opt,name=proof_ger_l1root,json=proofGerL1root,proto3" json:"proof_ger_l1root,omitempty"`
	// L1InfoTree leaf
	L1Leaf        *L1InfoTreeLeafWithContext `protobuf:"bytes,3,opt,name=l1_leaf,json=l1Leaf,proto3" json:"l1_leaf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimFromMainnet) Reset() {
	*x = ClaimFromMainnet{}
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimFromMainnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimFromMainnet) ProtoMessage() {}

func (x *ClaimFromMainnet) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimFromMainnet.ProtoReflect.Descriptor instead.
func (*ClaimFromMainnet) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_claim_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimFromMainnet) GetProofLeafMer() *MerkleProof {
	if x != nil {
		return x.ProofLeafMer
	}
	return nil
}

func (x *ClaimFromMainnet) GetProofGerL1Root() *MerkleProof {
	if x != nil {
		return x.ProofGerL1Root
	}
	return nil
}

func (x *ClaimFromMainnet) GetL1Leaf() *L1InfoTreeLeafWithContext {
	if x != nil {
		return x.L1Leaf
	}
	return nil
}

// Represents a leaf in the L1InfoTree with its context.
type L1InfoTreeLeafWithContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// l1 info tree leaf index
	L1InfoTreeIndex uint32 `protobuf:"varint,1,opt,name=l1_info_tree_index,json=l1InfoTreeIndex,proto3" json:"l1_info_tree_index,omitempty"`
	// Rollup exit root
	Rer *FixedBytes32 `protobuf:"bytes,2,opt,name=rer,proto3" json:"rer,omitempty"`
	// Mainnet exit root
	Mer *FixedBytes32 `protobuf:"bytes,3,opt,name=mer,proto3" json:"mer,omitempty"`
	// Inner leaf
	Inner         *L1InfoTreeLeaf `protobuf:"bytes,4,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L1InfoTreeLeafWithContext) Reset() {
	*x = L1InfoTreeLeafWithContext{}
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L1InfoTreeLeafWithContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1InfoTreeLeafWithContext) ProtoMessage() {}

func (x *L1InfoTreeLeafWithContext) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1InfoTreeLeafWithContext.ProtoReflect.Descriptor instead.
func (*L1InfoTreeLeafWithContext) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_claim_proto_rawDescGZIP(), []int{1}
}

func (x *L1InfoTreeLeafWithContext) GetL1InfoTreeIndex() uint32 {
	if x != nil {
		return x.L1InfoTreeIndex
	}
	return 0
}

func (x *L1InfoTreeLeafWithContext) GetRer() *FixedBytes32 {
	if x != nil {
		return x.Rer
	}
	return nil
}

func (x *L1InfoTreeLeafWithContext) GetMer() *FixedBytes32 {
	if x != nil {
		return x.Mer
	}
	return nil
}

func (x *L1InfoTreeLeafWithContext) GetInner() *L1InfoTreeLeaf {
	if x != nil {
		return x.Inner
	}
	return nil
}

// Represents the leaf in the L1InfoTree.
type L1InfoTreeLeaf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The global exit root.
	GlobalExitRoot *FixedBytes32 `protobuf:"bytes,1,opt,name=global_exit_root,json=globalExitRoot,proto3" json:"global_exit_root,omitempty"`
	// Block hash.
	BlockHash *FixedBytes32 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Timestamp.
	Timestamp     uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L1InfoTreeLeaf) Reset() {
	*x = L1InfoTreeLeaf{}
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L1InfoTreeLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1InfoTreeLeaf) ProtoMessage() {}

func (x *L1InfoTreeLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1InfoTreeLeaf.ProtoReflect.Descriptor instead.
func (*L1InfoTreeLeaf) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_claim_proto_rawDescGZIP(), []int{2}
}

func (x *L1InfoTreeLeaf) GetGlobalExitRoot() *FixedBytes32 {
	if x != nil {
		return x.GlobalExitRoot
	}
	return nil
}

func (x *L1InfoTreeLeaf) GetBlockHash() *FixedBytes32 {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *L1InfoTreeLeaf) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Represents a claim from the rollup.
type ClaimFromRollup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Proof from bridge exit leaf to LER
	ProofLeafLer *MerkleProof `protobuf:"bytes,1,opt,name=proof_leaf_ler,json=proofLeafLer,proto3" json:"proof_leaf_ler,omitempty"`
	// Proof from LER to RER
	ProofLerRer *MerkleProof `protobuf:"bytes,2,opt,name=proof_ler_rer,json=proofLerRer,proto3" json:"proof_ler_rer,omitempty"`
	// Proof from GER to L1Root
	ProofGerL1Root *MerkleProof `protobuf:"bytes,3,opt,name=proof_ger_l1root,json=proofGerL1root,proto3" json:"proof_ger_l1root,omitempty"`
	// L1InfoTree leaf
	L1Leaf        *L1InfoTreeLeafWithContext `protobuf:"bytes,4,opt,name=l1_leaf,json=l1Leaf,proto3" json:"l1_leaf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimFromRollup) Reset() {
	*x = ClaimFromRollup{}
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimFromRollup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimFromRollup) ProtoMessage() {}

func (x *ClaimFromRollup) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_claim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimFromRollup.ProtoReflect.Descriptor instead.
func (*ClaimFromRollup) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_claim_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimFromRollup) GetProofLeafLer() *MerkleProof {
	if x != nil {
		return x.ProofLeafLer
	}
	return nil
}

func (x *ClaimFromRollup) GetProofLerRer() *MerkleProof {
	if x != nil {
		return x.ProofLerRer
	}
	return nil
}

func (x *ClaimFromRollup) GetProofGerL1Root() *MerkleProof {
	if x != nil {
		return x.ProofGerL1Root
	}
	return nil
}

func (x *ClaimFromRollup) GetL1Leaf() *L1InfoTreeLeafWithContext {
	if x != nil {
		return x.L1Leaf
	}
	return nil
}

var File_agglayer_interop_types_v1_claim_proto protoreflect.FileDescriptor

const file_agglayer_interop_types_v1_claim_proto_rawDesc = "" +
	"\n" +
	"%agglayer/interop/types/v1/claim.proto\x12\x19agglayer.interop.types.v1\x1a%agglayer/interop/types/v1/bytes.proto\x1a,agglayer/interop/types/v1/merkle_proof.proto\"\x81\x02\n" +
	"\x10ClaimFromMainnet\x12L\n" +
	"\x0eproof_leaf_mer\x18\x01 \x01(\v2&.agglayer.interop.types.v1.MerkleProofR\fproofLeafMer\x12P\n" +
	"\x10proof_ger_l1root\x18\x02 \x01(\v2&.agglayer.interop.types.v1.MerkleProofR\x0eproofGerL1root\x12M\n" +
	"\al1_leaf\x18\x03 \x01(\v24.agglayer.interop.types.v1.L1InfoTreeLeafWithContextR\x06l1Leaf\"\xff\x01\n" +
	"\x19L1InfoTreeLeafWithContext\x12+\n" +
	"\x12l1_info_tree_index\x18\x01 \x01(\rR\x0fl1InfoTreeIndex\x129\n" +
	"\x03rer\x18\x02 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\x03rer\x129\n" +
	"\x03mer\x18\x03 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\x03mer\x12?\n" +
	"\x05inner\x18\x04 \x01(\v2).agglayer.interop.types.v1.L1InfoTreeLeafR\x05inner\"\xc9\x01\n" +
	"\x0eL1InfoTreeLeaf\x12Q\n" +
	"\x10global_exit_root\x18\x01 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\x0eglobalExitRoot\x12F\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\tblockHash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"\xcc\x02\n" +
	"\x0fClaimFromRollup\x12L\n" +
	"\x0eproof_leaf_ler\x18\x01 \x01(\v2&.agglayer.interop.types.v1.MerkleProofR\fproofLeafLer\x12J\n" +
	"\rproof_ler_rer\x18\x02 \x01(\v2&.agglayer.interop.types.v1.MerkleProofR\vproofLerRer\x12P\n" +
	"\x10proof_ger_l1root\x18\x03 \x01(\v2&.agglayer.interop.types.v1.MerkleProofR\x0eproofGerL1root\x12M\n" +
	"\al1_leaf\x18\x04 \x01(\v24.agglayer.interop.types.v1.L1InfoTreeLeafWithContextR\x06l1Leafb\x06proto3"

var (
	file_agglayer_interop_types_v1_claim_proto_rawDescOnce sync.Once
	file_agglayer_interop_types_v1_claim_proto_rawDescData []byte
)

func file_agglayer_interop_types_v1_claim_proto_rawDescGZIP() []byte {
	file_agglayer_interop_types_v1_claim_proto_rawDescOnce.Do(func() {
		file_agglayer_interop_types_v1_claim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_claim_proto_rawDesc), len(file_agglayer_interop_types_v1_claim_proto_rawDesc)))
	})
	return file_agglayer_interop_types_v1_claim_proto_rawDescData
}

var file_agglayer_interop_types_v1_claim_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agglayer_interop_types_v1_claim_proto_goTypes = []any{
	(*ClaimFromMainnet)(nil),          // 0: agglayer.interop.types.v1.ClaimFromMainnet
	(*L1InfoTreeLeafWithContext)(nil), // 1: agglayer.interop.types.v1.L1InfoTreeLeafWithContext
	(*L1InfoTreeLeaf)(nil),            // 2: agglayer.interop.types.v1.L1InfoTreeLeaf
	(*ClaimFromRollup)(nil),           // 3: agglayer.interop.types.v1.ClaimFromRollup
	(*MerkleProof)(nil),               // 4: agglayer.interop.types.v1.MerkleProof
	(*FixedBytes32)(nil),              // 5: agglayer.interop.types.v1.FixedBytes32
}
var file_agglayer_interop_types_v1_claim_proto_depIdxs = []int32{
	4,  // 0: agglayer.interop.types.v1.ClaimFromMainnet.proof_leaf_mer:type_name -> agglayer.interop.types.v1.MerkleProof
	4,  // 1: agglayer.interop.types.v1.ClaimFromMainnet.proof_ger_l1root:type_name -> agglayer.interop.types.v1.MerkleProof
	1,  // 2: agglayer.interop.types.v1.ClaimFromMainnet.l1_leaf:type_name -> agglayer.interop.types.v1.L1InfoTreeLeafWithContext
	5,  // 3: agglayer.interop.types.v1.L1InfoTreeLeafWithContext.rer:type_name -> agglayer.interop.types.v1.FixedBytes32
	5,  // 4: agglayer.interop.types.v1.L1InfoTreeLeafWithContext.mer:type_name -> agglayer.interop.types.v1.FixedBytes32
	2,  // 5: agglayer.interop.types.v1.L1InfoTreeLeafWithContext.inner:type_name -> agglayer.interop.types.v1.L1InfoTreeLeaf
	5,  // 6: agglayer.interop.types.v1.L1InfoTreeLeaf.global_exit_root:type_name -> agglayer.interop.types.v1.FixedBytes32
	5,  // 7: agglayer.interop.types.v1.L1InfoTreeLeaf.block_hash:type_name -> agglayer.interop.types.v1.FixedBytes32
	4,  // 8: agglayer.interop.types.v1.ClaimFromRollup.proof_leaf_ler:type_name -> agglayer.interop.types.v1.MerkleProof
	4,  // 9: agglayer.interop.types.v1.ClaimFromRollup.proof_ler_rer:type_name -> agglayer.interop.types.v1.MerkleProof
	4,  // 10: agglayer.interop.types.v1.ClaimFromRollup.proof_ger_l1root:type_name -> agglayer.interop.types.v1.MerkleProof
	1,  // 11: agglayer.interop.types.v1.ClaimFromRollup.l1_leaf:type_name -> agglayer.interop.types.v1.L1InfoTreeLeafWithContext
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_agglayer_interop_types_v1_claim_proto_init() }
func file_agglayer_interop_types_v1_claim_proto_init() {
	if File_agglayer_interop_types_v1_claim_proto != nil {
		return
	}
	file_agglayer_interop_types_v1_bytes_proto_init()
	file_agglayer_interop_types_v1_merkle_proof_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_claim_proto_rawDesc), len(file_agglayer_interop_types_v1_claim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agglayer_interop_types_v1_claim_proto_goTypes,
		DependencyIndexes: file_agglayer_interop_types_v1_claim_proto_depIdxs,
		MessageInfos:      file_agglayer_interop_types_v1_claim_proto_msgTypes,
	}.Build()
	File_agglayer_interop_types_v1_claim_proto = out.File
	file_agglayer_interop_types_v1_claim_proto_goTypes = nil
	file_agglayer_interop_types_v1_claim_proto_depIdxs = nil
}
