// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agglayer/interop/types/v1/merkle_proof.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a Merkle proof.
type MerkleProof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The root of the Merkle tree.
	Root *FixedBytes32 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// The path from the leaf to the root.
	Siblings      []*FixedBytes32 `protobuf:"bytes,2,rep,name=siblings,proto3" json:"siblings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProof) Reset() {
	*x = MerkleProof{}
	mi := &file_agglayer_interop_types_v1_merkle_proof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProof) ProtoMessage() {}

func (x *MerkleProof) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_interop_types_v1_merkle_proof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProof.ProtoReflect.Descriptor instead.
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return file_agglayer_interop_types_v1_merkle_proof_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleProof) GetRoot() *FixedBytes32 {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *MerkleProof) GetSiblings() []*FixedBytes32 {
	if x != nil {
		return x.Siblings
	}
	return nil
}

var File_agglayer_interop_types_v1_merkle_proof_proto protoreflect.FileDescriptor

const file_agglayer_interop_types_v1_merkle_proof_proto_rawDesc = "" +
	"\n" +
	",agglayer/interop/types/v1/merkle_proof.proto\x12\x19agglayer.interop.types.v1\x1a%agglayer/interop/types/v1/bytes.proto\"\x8f\x01\n" +
	"\vMerkleProof\x12;\n" +
	"\x04root\x18\x01 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\x04root\x12C\n" +
	"\bsiblings\x18\x02 \x03(\v2'.agglayer.interop.types.v1.FixedBytes32R\bsiblingsb\x06proto3"

var (
	file_agglayer_interop_types_v1_merkle_proof_proto_rawDescOnce sync.Once
	file_agglayer_interop_types_v1_merkle_proof_proto_rawDescData []byte
)

func file_agglayer_interop_types_v1_merkle_proof_proto_rawDescGZIP() []byte {
	file_agglayer_interop_types_v1_merkle_proof_proto_rawDescOnce.Do(func() {
		file_agglayer_interop_types_v1_merkle_proof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_merkle_proof_proto_rawDesc), len(file_agglayer_interop_types_v1_merkle_proof_proto_rawDesc)))
	})
	return file_agglayer_interop_types_v1_merkle_proof_proto_rawDescData
}

var file_agglayer_interop_types_v1_merkle_proof_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agglayer_interop_types_v1_merkle_proof_proto_goTypes = []any{
	(*MerkleProof)(nil),  // 0: agglayer.interop.types.v1.MerkleProof
	(*FixedBytes32)(nil), // 1: agglayer.interop.types.v1.FixedBytes32
}
var file_agglayer_interop_types_v1_merkle_proof_proto_depIdxs = []int32{
	1, // 0: agglayer.interop.types.v1.MerkleProof.root:type_name -> agglayer.interop.types.v1.FixedBytes32
	1, // 1: agglayer.interop.types.v1.MerkleProof.siblings:type_name -> agglayer.interop.types.v1.FixedBytes32
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agglayer_interop_types_v1_merkle_proof_proto_init() }
func file_agglayer_interop_types_v1_merkle_proof_proto_init() {
	if File_agglayer_interop_types_v1_merkle_proof_proto != nil {
		return
	}
	file_agglayer_interop_types_v1_bytes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agglayer_interop_types_v1_merkle_proof_proto_rawDesc), len(file_agglayer_interop_types_v1_merkle_proof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agglayer_interop_types_v1_merkle_proof_proto_goTypes,
		DependencyIndexes: file_agglayer_interop_types_v1_merkle_proof_proto_depIdxs,
		MessageInfos:      file_agglayer_interop_types_v1_merkle_proof_proto_msgTypes,
	}.Build()
	File_agglayer_interop_types_v1_merkle_proof_proto = out.File
	file_agglayer_interop_types_v1_merkle_proof_proto_goTypes = nil
	file_agglayer_interop_types_v1_merkle_proof_proto_depIdxs = nil
}
