// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agglayer/node/types/v1/certificate_id.proto

package v1

import (
	v1 "github.com/gateway-fm/agg-certificate-proxy/pkg/proto/agglayer/interop/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Certificate identifier.
type CertificateId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes representation of the certificate id.
	Value         *v1.FixedBytes32 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateId) Reset() {
	*x = CertificateId{}
	mi := &file_agglayer_node_types_v1_certificate_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateId) ProtoMessage() {}

func (x *CertificateId) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_node_types_v1_certificate_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateId.ProtoReflect.Descriptor instead.
func (*CertificateId) Descriptor() ([]byte, []int) {
	return file_agglayer_node_types_v1_certificate_id_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateId) GetValue() *v1.FixedBytes32 {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_agglayer_node_types_v1_certificate_id_proto protoreflect.FileDescriptor

const file_agglayer_node_types_v1_certificate_id_proto_rawDesc = "" +
	"\n" +
	"+agglayer/node/types/v1/certificate_id.proto\x12\x16agglayer.node.types.v1\x1a%agglayer/interop/types/v1/bytes.proto\"N\n" +
	"\rCertificateId\x12=\n" +
	"\x05value\x18\x01 \x01(\v2'.agglayer.interop.types.v1.FixedBytes32R\x05valueb\x06proto3"

var (
	file_agglayer_node_types_v1_certificate_id_proto_rawDescOnce sync.Once
	file_agglayer_node_types_v1_certificate_id_proto_rawDescData []byte
)

func file_agglayer_node_types_v1_certificate_id_proto_rawDescGZIP() []byte {
	file_agglayer_node_types_v1_certificate_id_proto_rawDescOnce.Do(func() {
		file_agglayer_node_types_v1_certificate_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agglayer_node_types_v1_certificate_id_proto_rawDesc), len(file_agglayer_node_types_v1_certificate_id_proto_rawDesc)))
	})
	return file_agglayer_node_types_v1_certificate_id_proto_rawDescData
}

var file_agglayer_node_types_v1_certificate_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agglayer_node_types_v1_certificate_id_proto_goTypes = []any{
	(*CertificateId)(nil),   // 0: agglayer.node.types.v1.CertificateId
	(*v1.FixedBytes32)(nil), // 1: agglayer.interop.types.v1.FixedBytes32
}
var file_agglayer_node_types_v1_certificate_id_proto_depIdxs = []int32{
	1, // 0: agglayer.node.types.v1.CertificateId.value:type_name -> agglayer.interop.types.v1.FixedBytes32
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agglayer_node_types_v1_certificate_id_proto_init() }
func file_agglayer_node_types_v1_certificate_id_proto_init() {
	if File_agglayer_node_types_v1_certificate_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agglayer_node_types_v1_certificate_id_proto_rawDesc), len(file_agglayer_node_types_v1_certificate_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agglayer_node_types_v1_certificate_id_proto_goTypes,
		DependencyIndexes: file_agglayer_node_types_v1_certificate_id_proto_depIdxs,
		MessageInfos:      file_agglayer_node_types_v1_certificate_id_proto_msgTypes,
	}.Build()
	File_agglayer_node_types_v1_certificate_id_proto = out.File
	file_agglayer_node_types_v1_certificate_id_proto_goTypes = nil
	file_agglayer_node_types_v1_certificate_id_proto_depIdxs = nil
}
