// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agglayer/node/types/v1/epoch_configuration.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Epoch configuration type.
type EpochConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The genesis block of the epoch.
	GenesisBlock uint64 `protobuf:"varint,1,opt,name=genesis_block,json=genesisBlock,proto3" json:"genesis_block,omitempty"`
	// The epoch duration.
	EpochDuration uint64 `protobuf:"varint,2,opt,name=epoch_duration,json=epochDuration,proto3" json:"epoch_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochConfiguration) Reset() {
	*x = EpochConfiguration{}
	mi := &file_agglayer_node_types_v1_epoch_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochConfiguration) ProtoMessage() {}

func (x *EpochConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_agglayer_node_types_v1_epoch_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochConfiguration.ProtoReflect.Descriptor instead.
func (*EpochConfiguration) Descriptor() ([]byte, []int) {
	return file_agglayer_node_types_v1_epoch_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *EpochConfiguration) GetGenesisBlock() uint64 {
	if x != nil {
		return x.GenesisBlock
	}
	return 0
}

func (x *EpochConfiguration) GetEpochDuration() uint64 {
	if x != nil {
		return x.EpochDuration
	}
	return 0
}

var File_agglayer_node_types_v1_epoch_configuration_proto protoreflect.FileDescriptor

const file_agglayer_node_types_v1_epoch_configuration_proto_rawDesc = "" +
	"\n" +
	"0agglayer/node/types/v1/epoch_configuration.proto\x12\x16agglayer.node.types.v1\"`\n" +
	"\x12EpochConfiguration\x12#\n" +
	"\rgenesis_block\x18\x01 \x01(\x04R\fgenesisBlock\x12%\n" +
	"\x0eepoch_duration\x18\x02 \x01(\x04R\repochDurationb\x06proto3"

var (
	file_agglayer_node_types_v1_epoch_configuration_proto_rawDescOnce sync.Once
	file_agglayer_node_types_v1_epoch_configuration_proto_rawDescData []byte
)

func file_agglayer_node_types_v1_epoch_configuration_proto_rawDescGZIP() []byte {
	file_agglayer_node_types_v1_epoch_configuration_proto_rawDescOnce.Do(func() {
		file_agglayer_node_types_v1_epoch_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agglayer_node_types_v1_epoch_configuration_proto_rawDesc), len(file_agglayer_node_types_v1_epoch_configuration_proto_rawDesc)))
	})
	return file_agglayer_node_types_v1_epoch_configuration_proto_rawDescData
}

var file_agglayer_node_types_v1_epoch_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agglayer_node_types_v1_epoch_configuration_proto_goTypes = []any{
	(*EpochConfiguration)(nil), // 0: agglayer.node.types.v1.EpochConfiguration
}
var file_agglayer_node_types_v1_epoch_configuration_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agglayer_node_types_v1_epoch_configuration_proto_init() }
func file_agglayer_node_types_v1_epoch_configuration_proto_init() {
	if File_agglayer_node_types_v1_epoch_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agglayer_node_types_v1_epoch_configuration_proto_rawDesc), len(file_agglayer_node_types_v1_epoch_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agglayer_node_types_v1_epoch_configuration_proto_goTypes,
		DependencyIndexes: file_agglayer_node_types_v1_epoch_configuration_proto_depIdxs,
		MessageInfos:      file_agglayer_node_types_v1_epoch_configuration_proto_msgTypes,
	}.Build()
	File_agglayer_node_types_v1_epoch_configuration_proto = out.File
	file_agglayer_node_types_v1_epoch_configuration_proto_goTypes = nil
	file_agglayer_node_types_v1_epoch_configuration_proto_depIdxs = nil
}
