// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agglayer/node/v1/certificate_submission.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertificateSubmissionService_SubmitCertificate_FullMethodName = "/agglayer.node.v1.CertificateSubmissionService/SubmitCertificate"
)

// CertificateSubmissionServiceClient is the client API for CertificateSubmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for submitting certificate to an agglayer node.
type CertificateSubmissionServiceClient interface {
	// Method used to submit a certificate.
	SubmitCertificate(ctx context.Context, in *SubmitCertificateRequest, opts ...grpc.CallOption) (*SubmitCertificateResponse, error)
}

type certificateSubmissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateSubmissionServiceClient(cc grpc.ClientConnInterface) CertificateSubmissionServiceClient {
	return &certificateSubmissionServiceClient{cc}
}

func (c *certificateSubmissionServiceClient) SubmitCertificate(ctx context.Context, in *SubmitCertificateRequest, opts ...grpc.CallOption) (*SubmitCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCertificateResponse)
	err := c.cc.Invoke(ctx, CertificateSubmissionService_SubmitCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateSubmissionServiceServer is the server API for CertificateSubmissionService service.
// All implementations must embed UnimplementedCertificateSubmissionServiceServer
// for forward compatibility.
//
// Service for submitting certificate to an agglayer node.
type CertificateSubmissionServiceServer interface {
	// Method used to submit a certificate.
	SubmitCertificate(context.Context, *SubmitCertificateRequest) (*SubmitCertificateResponse, error)
	mustEmbedUnimplementedCertificateSubmissionServiceServer()
}

// UnimplementedCertificateSubmissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertificateSubmissionServiceServer struct{}

func (UnimplementedCertificateSubmissionServiceServer) SubmitCertificate(context.Context, *SubmitCertificateRequest) (*SubmitCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCertificate not implemented")
}
func (UnimplementedCertificateSubmissionServiceServer) mustEmbedUnimplementedCertificateSubmissionServiceServer() {
}
func (UnimplementedCertificateSubmissionServiceServer) testEmbeddedByValue() {}

// UnsafeCertificateSubmissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateSubmissionServiceServer will
// result in compilation errors.
type UnsafeCertificateSubmissionServiceServer interface {
	mustEmbedUnimplementedCertificateSubmissionServiceServer()
}

func RegisterCertificateSubmissionServiceServer(s grpc.ServiceRegistrar, srv CertificateSubmissionServiceServer) {
	// If the following call pancis, it indicates UnimplementedCertificateSubmissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertificateSubmissionService_ServiceDesc, srv)
}

func _CertificateSubmissionService_SubmitCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateSubmissionServiceServer).SubmitCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateSubmissionService_SubmitCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateSubmissionServiceServer).SubmitCertificate(ctx, req.(*SubmitCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateSubmissionService_ServiceDesc is the grpc.ServiceDesc for CertificateSubmissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateSubmissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agglayer.node.v1.CertificateSubmissionService",
	HandlerType: (*CertificateSubmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCertificate",
			Handler:    _CertificateSubmissionService_SubmitCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agglayer/node/v1/certificate_submission.proto",
}
