// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agglayer/node/v1/node_state.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeStateService_GetCertificateHeader_FullMethodName       = "/agglayer.node.v1.NodeStateService/GetCertificateHeader"
	NodeStateService_GetLatestCertificateHeader_FullMethodName = "/agglayer.node.v1.NodeStateService/GetLatestCertificateHeader"
)

// NodeStateServiceClient is the client API for NodeStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for querying node state.
type NodeStateServiceClient interface {
	// Method used to get a CertificateHeader for a particular CertificateId.
	GetCertificateHeader(ctx context.Context, in *GetCertificateHeaderRequest, opts ...grpc.CallOption) (*GetCertificateHeaderResponse, error)
	// Method used to get the latest known certificate header for a network.
	GetLatestCertificateHeader(ctx context.Context, in *GetLatestCertificateHeaderRequest, opts ...grpc.CallOption) (*GetLatestCertificateHeaderResponse, error)
}

type nodeStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeStateServiceClient(cc grpc.ClientConnInterface) NodeStateServiceClient {
	return &nodeStateServiceClient{cc}
}

func (c *nodeStateServiceClient) GetCertificateHeader(ctx context.Context, in *GetCertificateHeaderRequest, opts ...grpc.CallOption) (*GetCertificateHeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificateHeaderResponse)
	err := c.cc.Invoke(ctx, NodeStateService_GetCertificateHeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStateServiceClient) GetLatestCertificateHeader(ctx context.Context, in *GetLatestCertificateHeaderRequest, opts ...grpc.CallOption) (*GetLatestCertificateHeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestCertificateHeaderResponse)
	err := c.cc.Invoke(ctx, NodeStateService_GetLatestCertificateHeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeStateServiceServer is the server API for NodeStateService service.
// All implementations must embed UnimplementedNodeStateServiceServer
// for forward compatibility.
//
// Service for querying node state.
type NodeStateServiceServer interface {
	// Method used to get a CertificateHeader for a particular CertificateId.
	GetCertificateHeader(context.Context, *GetCertificateHeaderRequest) (*GetCertificateHeaderResponse, error)
	// Method used to get the latest known certificate header for a network.
	GetLatestCertificateHeader(context.Context, *GetLatestCertificateHeaderRequest) (*GetLatestCertificateHeaderResponse, error)
	mustEmbedUnimplementedNodeStateServiceServer()
}

// UnimplementedNodeStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeStateServiceServer struct{}

func (UnimplementedNodeStateServiceServer) GetCertificateHeader(context.Context, *GetCertificateHeaderRequest) (*GetCertificateHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificateHeader not implemented")
}
func (UnimplementedNodeStateServiceServer) GetLatestCertificateHeader(context.Context, *GetLatestCertificateHeaderRequest) (*GetLatestCertificateHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestCertificateHeader not implemented")
}
func (UnimplementedNodeStateServiceServer) mustEmbedUnimplementedNodeStateServiceServer() {}
func (UnimplementedNodeStateServiceServer) testEmbeddedByValue()                          {}

// UnsafeNodeStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeStateServiceServer will
// result in compilation errors.
type UnsafeNodeStateServiceServer interface {
	mustEmbedUnimplementedNodeStateServiceServer()
}

func RegisterNodeStateServiceServer(s grpc.ServiceRegistrar, srv NodeStateServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeStateService_ServiceDesc, srv)
}

func _NodeStateService_GetCertificateHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStateServiceServer).GetCertificateHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeStateService_GetCertificateHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStateServiceServer).GetCertificateHeader(ctx, req.(*GetCertificateHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStateService_GetLatestCertificateHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestCertificateHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStateServiceServer).GetLatestCertificateHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeStateService_GetLatestCertificateHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStateServiceServer).GetLatestCertificateHeader(ctx, req.(*GetLatestCertificateHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeStateService_ServiceDesc is the grpc.ServiceDesc for NodeStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agglayer.node.v1.NodeStateService",
	HandlerType: (*NodeStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCertificateHeader",
			Handler:    _NodeStateService_GetCertificateHeader_Handler,
		},
		{
			MethodName: "GetLatestCertificateHeader",
			Handler:    _NodeStateService_GetLatestCertificateHeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agglayer/node/v1/node_state.proto",
}
